format:
  line_width: 100
  tab_size: 2
  max_pargs_hwrap: 5
  max_subgroups_hwrap: 3
  enable_sort: true
  autosort: true
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: true
  line_ending: unix
markup:
  bullet_char: "*"
  enum_char: .
  enable_markup: false
