format:
  line_width: 120
  tab_size: 2
  max_pargs_hwrap: 3
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  line_ending: unix
markup:
  bullet_char: "*"
  enum_char: .
  enable_markup: false
