version: "0.2"
files:
  - "**/*"
ignorePaths:
  - pnpm-lock.yaml
  - .git/
  - dist/
useGitignore: true
language: en, en-GB
allowCompoundWords: true
enableGlobDot: true
words:
  - aarch
  - aminya
  - Amnet
  - anotherproj
  - applellvm
  - ARGN
  - armv
  - asan
  - awalsh
  - buildtools
  - ccache
  - ccmake
  - CETCOMPAT
  - choco
  - cmake
  - CMAKE
  - cmakelang
  - cmakelint
  - cmds
  - cond
  - CPATH
  - Cppcheck
  - cppcoreguidelines
  - cppdbg
  - CPPFLAGS
  - cpprc
  - cppreference
  - ctest
  - Cuda
  - DCMAKE
  - DCONFIGURE
  - DCROSS
  - DDEFAULT_TRIPLET
  - deps
  - DEXERCISE
  - DFAKE
  - DOPT
  - dpkg
  - DPROJECT
  - DREPO
  - DSHARED
  - DTARGET
  - DVCPKG
  - dyld
  - dylib
  - eabi
  - egor-tensin
  - Eigen
  - elif
  - emcc
  - emcmake
  - emscripten
  - EMSDK
  - failifmismatch
  - fanalyzer
  - fargs
  - fcolor
  - fdiagnostics
  - fstack
  - ftime
  - gcovr
  - genex
  - GLIBCXX
  - gnueabi
  - gnueabihf
  - Graphviz
  - hwrap
  - iwwu
  - kcov
  - LDFLAGS
  - lgcc
  - libc
  - libcuda
  - libg
  - libstdc
  - LPSTR
  - LPWSTR
  - lrdimon
  - lstdc
  - mathjax
  - mcpu
  - mdfile
  - mfpu
  - moderncmakedomain
  - msbuild
  - msvc
  - msvcp
  - msys
  - mthumb
  - multilib
  - municode
  - myapp
  - mylib
  - mymindstorm
  - myprogram
  - myproj
  - myproject
  - mypy
  - mythirdpartylib
  - noexecstack
  - nojekyll
  - nosys
  - nothrow
  - nvcc
  - NXCOMPAT
  - Opencppcoverage
  - pargs
  - pipx
  - pkgs
  - pnpm
  - POSIX
  - pwsh
  - qthelp
  - relro
  - riscv
  - rmrf
  - rpath
  - rtti
  - sccache
  - servor
  - setx
  - shlib
  - suppr
  - SYSROOT
  - tecolicom
  - texi
  - TOLOWER
  - TOUPPER
  - ubsan
  - ucrtbased
  - undoc
  - vcpkg
  - vcvarsall
  - venv
  - visualc
  - visualcpp
  - VSCMD
  - VSINSTALLDIR
  - vsversion
  - Wanalyzer
  - Wcast
  - Wconversion
  - Wdouble
  - Wduplicated
  - Werror
  - Weverything
  - Wextra
  - Wformat
  - Wlogical
  - Wmisleading
  - Wnon
  - Wnull
  - Woverloaded
  - Wpedantic
  - Wshadow
  - Wsign
  - Wstrict
  - Wstringop
  - Wunused
  - Wuseless
  - Xcompiler
  - xcrun
  - Yahyaabadi
