cmake_minimum_required(VERSION 3.20)

foreach(REQUIRED_VARIABLE IN ITEMS
        FAKE_VCPKG_REPOSITORY
        SHARED_VCPKG_DIR
        CONFIGURE_A_BINARY_DIR
        CONFIGURE_B_BINARY_DIR
)
  if(NOT DEFINED ${REQUIRED_VARIABLE})
    message(FATAL_ERROR "${REQUIRED_VARIABLE} is required")
  endif()
endforeach()

find_program(GIT_EXECUTABLE git REQUIRED)
file(REMOVE_RECURSE "${SHARED_VCPKG_DIR}" "${CONFIGURE_A_BINARY_DIR}" "${CONFIGURE_B_BINARY_DIR}")
get_filename_component(SHARED_VCPKG_PARENT_DIR "${SHARED_VCPKG_DIR}" DIRECTORY)
file(MAKE_DIRECTORY "${SHARED_VCPKG_PARENT_DIR}")

execute_process(
  COMMAND "${GIT_EXECUTABLE}" clone "${FAKE_VCPKG_REPOSITORY}" "${SHARED_VCPKG_DIR}"
  WORKING_DIRECTORY "${SHARED_VCPKG_PARENT_DIR}"
  RESULT_VARIABLE CLONE_RESULT
  OUTPUT_VARIABLE CLONE_OUTPUT
  ERROR_VARIABLE CLONE_ERROR
)
if(CLONE_RESULT)
  message(FATAL_ERROR "Could not prepare shared fake vcpkg repository (${CLONE_RESULT}):\n"
                     "${CLONE_OUTPUT}\n${CLONE_ERROR}")
endif()
