set(args
    WARNINGS_AS_ERRORS
    ENABLE_COVERAGE
    ENABLE_CPPCHECK
    ENABLE_CLANG_TIDY
    ENABLE_INCLUDE_WHAT_YOU_USE
    ENABLE_CACHE
    ENABLE_PCH
    ENABLE_CONAN
    ENABLE_DOXYGEN
    ENABLE_IPO
    ENABLE_USER_LINKER
    ENABLE_BUILD_WITH_TIME_TRACE
    ENABLE_UNITY
    ENABLE_SANITIZER_ADDRESS
    ENABLE_SANITIZER_LEAK
    ENABLE_SANITIZER_UNDEFINED_BEHAVIOR
    ENABLE_SANITIZER_THREAD
    ENABLE_SANITIZER_MEMORY)
foreach(opt ${args})
  option(${opt} OFF)
  if(${opt})
    set(${opt} ${opt})
  else()
    unset(${opt})
  endif()
endforeach()
