include_guard()

macro(setup_project_options prefix)
  set(OPTIONS_PREFIX "${prefix}")

  option(OPTIONS_WARNINGS_AS_ERRORS "Warnings as errors" OFF)
  option(OPTIONS_ENABLE_COVERAGE "Enable coverage" OFF)
  option(OPTIONS_ENABLE_CPPCHECK "Enable CppCheck" OFF)
  option(OPTIONS_ENABLE_CLANG_TIDY "Enable clang-tidy" OFF)
  option(OPTIONS_ENABLE_VS_ANALYSIS "Enable VS analysis" OFF)
  option(OPTIONS_ENABLE_INCLUDE_WHAT_YOU_USE "Enable include-what-you-use" OFF)
  option(OPTIONS_ENABLE_CACHE "Enable cache" OFF)
  option(OPTIONS_ENABLE_PCH "Enable PCH" OFF)
  option(OPTIONS_ENABLE_CONAN "Enable Conan" OFF)
  option(OPTIONS_ENABLE_VCPKG "Enable vcpkg" OFF)
  option(OPTIONS_ENABLE_DOXYGEN "Enable Doxygen" OFF)
  option(OPTIONS_ENABLE_INTERPROCEDURAL_OPTIMIZATION "Enable interprocedural optimization" OFF)
  option(OPTIONS_ENABLE_NATIVE_OPTIMIZATION "Enable native optimization" OFF)
  option(OPTIONS_DISABLE_EXCEPTIONS "Disable exceptions" OFF)
  option(OPTIONS_DISABLE_RTTI "Disable RTTI" OFF)
  option(OPTIONS_ENABLE_BUILD_WITH_TIME_TRACE "Enable build with time trace" OFF)
  option(OPTIONS_ENABLE_UNITY "Enable Unity" OFF)
  option(OPTIONS_ENABLE_SANITIZER_ADDRESS "Enable sanitizer address" OFF)
  option(OPTIONS_ENABLE_SANITIZER_LEAK "Enable sanitizer leak" OFF)
  option(OPTIONS_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR "Enable sanitizer undefined behavior" OFF)
  option(OPTIONS_ENABLE_SANITIZER_THREAD "Enable sanitizer thread" OFF)
  option(OPTIONS_ENABLE_SANITIZER_MEMORY "Enable sanitizer memory" OFF)
  option(OPTIONS_LINKER "Linker" "")
  option(OPTIONS_VS_ANALYSIS_RULESET "VS analysis ruleset" "")
  option(OPTIONS_CONAN_PROFILE "Conan profile" "")
  option(OPTIONS_CONAN_HOST_PROFILE "Conan host profile" "")
  option(OPTIONS_CONAN_BUILD_PROFILE "Conan build profile" "")

  if(OPTIONS_WARNINGS_AS_ERRORS)
    set(WARNINGS_AS_ERRORS WARNINGS_AS_ERRORS)
  endif()
  if(OPTIONS_ENABLE_COVERAGE)
    set(ENABLE_COVERAGE ENABLE_COVERAGE)
  endif()
  if(OPTIONS_ENABLE_CPPCHECK)
    set(ENABLE_CPPCHECK ENABLE_CPPCHECK)
  endif()
  if(OPTIONS_ENABLE_CLANG_TIDY)
    set(ENABLE_CLANG_TIDY ENABLE_CLANG_TIDY)
  endif()
  if(OPTIONS_ENABLE_VS_ANALYSIS)
    set(ENABLE_VS_ANALYSIS ENABLE_VS_ANALYSIS)
  endif()
  if(OPTIONS_ENABLE_INCLUDE_WHAT_YOU_USE)
    set(ENABLE_INCLUDE_WHAT_YOU_USE ENABLE_INCLUDE_WHAT_YOU_USE)
  endif()
  if(OPTIONS_ENABLE_CACHE)
    set(ENABLE_CACHE ENABLE_CACHE)
  endif()
  if(OPTIONS_ENABLE_PCH)
    set(ENABLE_PCH ENABLE_PCH)
  endif()
  if(OPTIONS_ENABLE_CONAN)
    set(ENABLE_CONAN ENABLE_CONAN)
  endif()
  if(OPTIONS_ENABLE_VCPKG)
    set(ENABLE_VCPKG ENABLE_VCPKG)
  endif()
  if(OPTIONS_ENABLE_DOXYGEN)
    set(ENABLE_DOXYGEN ENABLE_DOXYGEN)
  endif()
  if(OPTIONS_ENABLE_INTERPROCEDURAL_OPTIMIZATION)
    set(ENABLE_INTERPROCEDURAL_OPTIMIZATION ENABLE_INTERPROCEDURAL_OPTIMIZATION)
  endif()
  if(OPTIONS_ENABLE_NATIVE_OPTIMIZATION)
    set(ENABLE_NATIVE_OPTIMIZATION ENABLE_NATIVE_OPTIMIZATION)
  endif()
  if(OPTIONS_DISABLE_EXCEPTIONS)
    set(DISABLE_EXCEPTIONS DISABLE_EXCEPTIONS)
  endif()
  if(OPTIONS_DISABLE_RTTI)
    set(DISABLE_RTTI DISABLE_RTTI)
  endif()
  if(OPTIONS_ENABLE_BUILD_WITH_TIME_TRACE)
    set(ENABLE_BUILD_WITH_TIME_TRACE ENABLE_BUILD_WITH_TIME_TRACE)
  endif()
  if(OPTIONS_ENABLE_UNITY)
    set(ENABLE_UNITY ENABLE_UNITY)
  endif()
  if(OPTIONS_ENABLE_SANITIZER_ADDRESS)
    set(ENABLE_SANITIZER_ADDRESS ENABLE_SANITIZER_ADDRESS)
  endif()
  if(OPTIONS_ENABLE_SANITIZER_LEAK)
    set(ENABLE_SANITIZER_LEAK ENABLE_SANITIZER_LEAK)
  endif()
  if(OPTIONS_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR)
    set(ENABLE_SANITIZER_UNDEFINED_BEHAVIOR ENABLE_SANITIZER_UNDEFINED_BEHAVIOR)
  endif()
  if(OPTIONS_ENABLE_SANITIZER_THREAD)
    set(ENABLE_SANITIZER_THREAD ENABLE_SANITIZER_THREAD)
  endif()
  if(OPTIONS_ENABLE_SANITIZER_MEMORY)
    set(ENABLE_SANITIZER_MEMORY ENABLE_SANITIZER_MEMORY)
  endif()
  if(OPTIONS_PREFIX)
    set(PREFIX "PREFIX" "${OPTIONS_PREFIX}")
  endif()
  if(OPTIONS_LINKER)
    set(LINKER "LINKER" "${OPTIONS_LINKER}")
  endif()
  if(OPTIONS_VS_ANALYSIS_RULESET)
    set(VS_ANALYSIS_RULESET "VS_ANALYSIS_RULESET" "${OPTIONS_VS_ANALYSIS_RULESET")
  endif()
  if(OPTIONS_CONAN_PROFILE)
    set(CONAN_PROFILE "CONAN_PROFILE" "${OPTIONS_CONAN_PROFILE}")
  endif()
  if(OPTIONS_CONAN_HOST_PROFILE)
    set(CONAN_HOST_PROFILE "CONAN_HOST_PROFILE" "${OPTIONS_CONAN_HOST_PROFILE}")
  endif()
  if(OPTIONS_CONAN_BUILD_PROFILE)
    set(CONAN_BUILD_PROFILE "CONAN_BUILD_PROFILE" "${OPTIONS_CONAN_BUILD_PROFILE}")
  endif()

  project_options(
    # Flags
    ${WARNINGS_AS_ERRORS}
    ${ENABLE_COVERAGE}
    ${ENABLE_CPPCHECK}
    ${ENABLE_CLANG_TIDY}
    ${ENABLE_VS_ANALYSIS}
    ${ENABLE_INCLUDE_WHAT_YOU_USE}
    ${ENABLE_CACHE}
    ${ENABLE_PCH}
    ${ENABLE_CONAN}
    ${ENABLE_VCPKG}
    ${ENABLE_DOXYGEN}
    ${ENABLE_INTERPROCEDURAL_OPTIMIZATION}
    ${ENABLE_NATIVE_OPTIMIZATION}
	${DISABLE_EXCEPTIONS}
	${DISABLE_RTTI}
    ${ENABLE_BUILD_WITH_TIME_TRACE}
    ${ENABLE_UNITY}
    ${ENABLE_SANITIZER_ADDRESS}
    ${ENABLE_SANITIZER_LEAK}
    ${ENABLE_SANITIZER_UNDEFINED_BEHAVIOR}
    ${ENABLE_SANITIZER_THREAD}
    ${ENABLE_SANITIZER_MEMORY}
    # Varaibles
	${PREFIX}
    ${LINKER}
    ${VS_ANALYSIS_RULESET}
    ${CONAN_PROFILE}
	${CONAN_HOST_PROFILE}
	${CONAN_BUILD_PROFILE}
    # Lists
	#DOXYGEN_THEME
    #MSVC_WARNINGS
    #CLANG_WARNINGS
    #GCC_WARNINGS
    #CUDA_WARNINGS
    #CPPCHECK_OPTIONS
    #CLANG_TIDY_EXTRA_ARGUMENTS
    #PCH_HEADERS
    #CONAN_OPTIONS
  )

endmacro()
